name: Electron Release

# This workflow is responsible for automatically building and releasing the electron app on pushes to the master branch. Build specific configurations are set in electron-builder.yml. 

# When ready to release a new version:
# 1. create a draft release and set tag to the new version
# 2. adjust version in package.json
# 3. commit
# 4. tag commit with the new version (ie. v4.0.0) - version must be prefixed by "v"
# 5. push commit and tag (git push && git push --tags)
# 6. This workflow should be triggered and in about 8 minutes the binaries will be available in the release draft

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  # create:
  #   branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: npm

      - name: Publish releases
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true