name: Electron Release

# This workflow is responsible for automatically building and releasing the electron app on pushes to the main branch. Build specific configurations are set in electron-builder.yml. 
#
# When ready to release a new version:
# 1. create a draft release and set tag to the new version
# 2. adjust version in package.json
# 3. commit
# 4. tag commit with the new version (ie. v4.0.0) - version must be prefixed by "v"
# 5. push commit and tag (git push && git push --tags)
# 6. This workflow should be triggered and in about 8 minutes the binaries will be available in the release draft

on:
  push:
    branches: [main]
    tags:
      - v*

  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0
        
      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
            
      - name: Install Dependencies
        run: npm install
          
      - name: Build/release Electron app
        uses: ResearchHelper/action-electron-builder@master
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # release after build
          release: true